model_name: 'efficientnet-b0'
image_size: 28
batch_size: 64

train_dir: train_${model_name}_${lr}_${batch_size}

model:
  module: models/EffNet
  options:
    model_name: ${model_name}
    image_size: ${image_size}
    num_classes: ${num_classes}
