channels: 1
width: 28
height: 28
hidden_size: 128
dropout: 0.1
batch_size: 64

train_dir: train_mlp_${lr}_${batch_size}

model:
  module: models/MLP
  options:
    channels: ${channels}
    width: ${width}
    height: ${height}
    hidden_size: ${hidden_size}
    num_classes: ${num_classes}
    dropout: ${dropout}
