#!/bin/env inex

# ./train.yaml -s . -m mlp.yaml
# ./train.yaml -s . -m effnet.yaml
# ./train.yaml -s . -m effnet.yaml -u lr=0.0004 -u num_epochs=5
# ./train.yaml -s . -m effnet.yaml -u lr=0.00064 -u batch_size=64 -u num_epochs=10 -u train_loader.options.num_workers=4
# ./train.yaml -s . -m effnet.yaml -u lr=0.00064 -u batch_size=64 -u num_epochs=10 -u train_loader.options.num_workers=4 -u model.options.dropout_rate=0.2

data_dir: data
train_dir: train

accelerator: gpu
devices: 1

num_classes: 10
batch_size: 32
lr: 0.0002
num_epochs: 3

plugins:
  - to_tensor
  - normalize
  - transform
  - train_set
  - train_loader
  - valid_set
  - valid_loader
  - model
  - parameters
  - optimizer
  - scheduler
  - criterion
  - accuracy
  - module
  - checkpoint
  - strategy
  - logger
  - progress
  - trainer

to_tensor:
  module: torchvision.transforms/ToTensor

normalize:
  module: torchvision.transforms/Normalize
  options:
    mean: [0.1307]
    std: [0.3081]

transform:
  module: torchvision.transforms/Compose
  imports:
    transforms: [plugins.to_tensor, plugins.normalize]

train_set:
  module: torchvision.datasets/MNIST
  imports:
    transform: plugins.transform
  options:
    root: ${data_dir}
    train: true
    download: true

train_loader:
  module: torch.utils.data/DataLoader
  imports:
    dataset: plugins.train_set
  options:
    batch_size: ${batch_size}

valid_set:
  module: torchvision.datasets/MNIST
  imports:
    transform: plugins.transform
  options:
    root: ${data_dir}
    train: false
    download: true

valid_loader:
  module: torch.utils.data/DataLoader
  imports:
    dataset: plugins.valid_set
  options:
    batch_size: ${batch_size}

parameters:
  module: plugins.model/parameters

optimizer:
  module: torch.optim/Adam
  imports:
    params: plugins.parameters
  options:
    lr: ${lr}

scheduler:
  module: torch.optim.lr_scheduler/OneCycleLR
  imports:
    optimizer: plugins.optimizer
  exports: []
  options:
    max_lr: ${lr}
    total_steps: ${num_epochs}

criterion:
  module: torch.nn/NLLLoss

accuracy:
  module: torchmetrics/Accuracy
  options:
    task: multiclass
    num_classes: ${num_classes}

module:
  module: module/Module
  imports:
    model: plugins.model
    optimizer: plugins.optimizer
    scheduler: plugins.scheduler
    criterion: plugins.criterion
    accuracy: plugins.accuracy

checkpoint:
  module: pytorch_lightning.callbacks/ModelCheckpoint
  options:
    dirpath: ${train_dir}
    monitor: 'val_acc'
    mode: 'max'
    save_top_k: 3

strategy:
  module: ines.helpers/none

logger:
  module: pytorch_lightning.loggers/CSVLogger
  options:
    save_dir: ${train_dir}

progress:
  module: pytorch_lightning.callbacks.progress/TQDMProgressBar
  options:
    refresh_rate: 20

trainer:
  module: pytorch_lightning/Trainer
  imports:
    logger: plugins.logger
    callbacks: [plugins.progress, plugins.checkpoint]
    strategy: plugins.strategy
  options:
    accelerator: ${accelerator}
    devices: ${devices}
    max_epochs: ${num_epochs}

execute:
  method: plugins.trainer/fit
  imports:
    model: plugins.module
    train_dataloaders: plugins.train_loader
    val_dataloaders: plugins.valid_loader