#!/bin/env inex

plugins:
  - tensor
  - add
  - sum

# numpy.array(object, ...)
tensor:
  module: numpy/array
  options:
    object: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# numpy.add(x1, x2, ...)
add:
  module: numpy/add
#  imports:
#    x1: plugins.tensor
  options:
#    x2: [[9, 8, 7], [6, 5, 4], [3, 2, 1]]
    x1: 1
    x2: 1

# numpy.sum(a, axis=None, ...)
sum:
  module: numpy/sum
  imports:
    a: plugins.add
  options:
    axis: 1

# def show(**kwargs):
#   for key, value in kwargs.items():
#     print(f'\n{key}\n  type: {type(value)}\n  value: {value}')
execute:
  method: inex.helpers/show
  imports:
    result: plugins.sum